### ISSUE TITLE
Using this docker

### ISSUE THREAD

**Issue by gnthibault** [dstndstn/nova-docker#1]
Hey,

First, I would like to thank you for this fantastic job (astrometry.net).

I tried to build the docker image, and it looked like some things went wrong while building astrometry.net, 

Makefile:61: makefile.os-features: No such file or directory
../util/makefile.deps:44: deps: No such file or directory
Makefile:432: cairoutils.dep: No such file or directory
Package gsl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gsl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gsl' found
make[1]: [report] Error 1 (ignored)

Did you experienced such problem ?
Thank you in advance for your help

**Comment by dstndstn** [comment]
I believe those are all expect errors that are correctly ignored by the build script.  Did it run to completion?

(makefile.os-features is auto-generated; but make complains that it does not exist before it generates it.  Same with the "deps" files.  For gsl, we can either use a system-installed one, or there is a subset of gsl shipped with astrometry.net -- the messages about gsl are just "make" looking for the system-installed gsl but not finding it; it will then use the shipped version)

**Comment by gnthibault** [comment]
Dear dstndstn, thank you very much for your answer.
By security, I added gsl-dev to the dockerfile, and it looks like the build is fine.
Unfortunately, I haven't found the documentation that explains how/where the index file should be added to this docker image.
And it also looks like no server is listening to port 80 from outside (I ran netstat -lt on my michanie while docker was running).

Is there something I am doing wrong ?

Thank you in advance for your time

**Comment by dstndstn** [comment]
Hi,
It looks like we copy an example index file into /INDEXES;
https://github.com/dstndstn/nova-docker/blob/master/Dockerfile#L68

I am a docker newbie, so I did not figure out how to make the apache process in the docker listen on an external port.  If you figure it out, I would be very happy to hear how to do it!

cheers,
--dustin

**Comment by gnthibault** [comment]
According to docker documentation:
https://docs.docker.com/engine/reference/builder/#expose

Using EXPOSE 80 as you did looks fine, however, I was wondering if something else was wrong, I will try to see if there are any logs that I can access on the docker image.

Do you know where I can download all the other index files ?

**Comment by dstndstn** [comment]
http://data.astrometry.net/

**Comment by gnthibault** [comment]
I cannot access the apache server on the docker, and the logs in /var/log/apache2/access.log/error.log are empty.
Any idea ?

Thank you for your help

**Comment by dstndstn** [comment]
sorry, no idea

**Comment by gnthibault** [comment]
Shame on me...
I forgot to use the port forwarding option when launching docker run:
`docker run -d -p 80:80 astrometryserver`

It looks like astrometry webserver frontend works fine now, you really did a great job at easing every users life, thank you again.

If I may add a small additional question now, it looks like I cannot login on the local astrometry server, which is probably the expected behaviour, as I did not filled the auth.py file.
Where could I find my google/github secrets to update the lcoal database, or even better, add my current API key to the docker database, so that I can submit jobs transparently both on local/nova server ?

Thank you for your help !

PS: here is the error I get when trying to login on the local server:


```
Request URL: | http://localhost/signin/
-- | --
1.8.7
ImportError
No module named social_core.backends.utils
/src/astrometry/astrometry/net/views/home.py in signin, line 47
/usr/bin/python
2.7.12
['/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/src/astrometry/net',  '/src/astrometry']

```

**Comment by dstndstn** [comment]
Wow, you're making great progress!

Due to some changes in the astrometry.net code, I think you need:

pip install social-auth-core social-auth-app-django

Then to pre-install your API key, I think what you want to do is add it to the "net/fixtures" directory, like this file,
https://github.com/dstndstn/astrometry.net/blob/master/net/fixtures/initial_data.json

Good luck!

**Comment by gnthibault** [comment]
Thank you very much for your help!
I was able to launch a job to frontend, unfortunately, it looks like the server is now looping forever in the "processing_started" state.

Are there some logs that I can look at in order to check what is going wrong (index missing for instance ?) 

Thank you in advance.

**Comment by dstndstn** [comment]
Hi,

The web frontend just accepts submissions and puts them in a database -- the "process_submissions.py" script must get launched in the background to pull work from the database and actually run the jobs.  It looks like the Dockerfile does NOT run that.

In the nova site, we just run in a *screen* session:

cd nova/astrometry/net
export PYTHONPATH=${PYTHONPATH}:.
(for ((;;)); do python process_submissions.py -s 4 -j 16 > dj.log 2>&1; sleep 1; done) &

If you can figure out how to make the Dockerfile launch that automatically, that would be great!!  Maybe creating a systemd service is the cleanest way...?

**Comment by gnthibault** [comment]
It looks like it is not really a good practice to setup multiple server running in one docker.
However in this case it is sooo convenient.
I gave it a try, see my fork: https://github.com/gnthibault/nova-docker, and it looks like it i working (using nohup)

Looks like the process_submission it now launched, but for now it fails, this may be due to the fact that I don't have enough index files, I am currently downloading all from 4107 to 4119.
What I see in my client logs looks like this:

login ok
upload ok
processing_started None
processing_started current_date
status solving
status failed

I'll give you an update tomorrow.
Anyway, if the process_submission is launched but fails, it could be interesting to know where are the log files ?

Thank you for your help.

**Comment by dstndstn** [comment]
Hi,

The process_submissions.py script just writes to stdout and stderr, so I believe you will find the log file in
/src/astrometry/net/dj.log

(That's where you're redirecting it, here:
https://github.com/gnthibault/nova-docker/blob/master/process_submission.sh#L5  )

Nice work!  I hope you will send a Pull Request for all your fixes when you are done!

**Comment by gnthibault** [comment]
Ouch! the submission_process try to send a request via ssh to another (!) service:

Starting Job processing for Job 2
Creating directory /src/astrometry/net/data/jobs/0000/00000002
submission id 2
running: augment-xylist --downsample 2 --ra 180.0 --tweak-order 2 --scale-units arcsecperpix --scale-low 1.1662 --radius 1.0 --wcs wcs.fits --out /src/astrometry/net/data/jobs/0000/00000002/job.axy --image /src/astrometry/net/data/files/uploaded/82e/82e24a7422842b5c44484180e6cd532af0aadbb4 --dec 45.0 --rdls rdls.fits --scale-high 1.2138 --corr corr.fits 
created axy file /src/astrometry/net/data/jobs/0000/00000002/job.axy
command: (echo job-test-2; tar cf - --ignore-failed-read -C /src/astrometry/net/data/jobs/0000/00000002 job.axy) | ssh -x -T an-docker 2>>/src/astrometry/net/data/jobs/0000/00000002/log | tar xf - --atime-preserve -m --exclude=job.axy -C /src/astrometry/net/data/jobs/0000/00000002 >>/src/astrometry/net/data/jobs/0000/00000002/log 2>&1
tar: -: Cannot write: Broken pipe
tar: Error is not recoverable: exiting now
Solver failed with return value 2
Call to solver failed for job 2 with return val 2
getlogger
Caught exception while processing Job 2
Traceback (most recent call last):
  File "process_submissions.py", line 184, in try_dojob
    solve_locally=solve_locally)
  File "process_submissions.py", line 364, in dojob
    raise Exception
Exception

Is it possible to call directly the service (synchronously) instead of trying to contact another server via ssh ?
Thank you in advance.

**Comment by gnthibault** [comment]
Ok, I just realized that there was a solve-locally option to the process_submission script.
I am re-running my example, and give you an update soon

EDIT1: I had to read the process_submission.py script, and found that the --solve-locally argument was not correctly mapped to any actual parameter (I changed that)

EDIT2: I realized that solve-locally, despite the name was not supposed to be a boolean, but the path to an application

EDIT3: I tried to understand the expected behaviour of the an-nova server that listen on the ssh tunnel, looking at this: http://astrometry.net/doc/nova.html
And it is very painful, what is the command that should be launched locally ? looks like it should be called backend, but no such binary is built by the project

EDIT4: last update fo rthis problem, got solution here: https://groups.google.com/forum/#!topic/astrometry/EjKj8zIafnQ

To quote Justin: 

> There is a script called "solvescript.sh" (https://github.com/dstndstn/nova-docker/blob/master/solvescript.sh)
> that is meant for this.  Run it like
> 
> python process_submissions.py --solve-locally=$(pwd)/solvescript.sh
> 
> There are some more details in this thread on a similar topic,
> 
> https://groups.google.com/d/msg/astrometry/4-ap6ssmvDU/OLL_NUJpBQAJ

So I just updated the process_submission.sh script, and I am now good to go with the API (I am not really using the web interface)

**Comment by typpo** [comment]
Chiming in here.  I've been able to start an instance, upload a picture, and solve a field.  In addition to @gnthibault's recent changes, I also had to add an `ALLOWED_HOSTS` variable to `settings.py` in order to cloud host this image and access it remotely.

I want to report some issues with the UI of the dockerized site.  Images don't show up on the results page.  For example [annotated_display/1](http://35.202.61.141/annotated_display/1) gives the following error:
```
Exception Type: | RuntimeError
-- | --
Error converting image file /src/astrometry/net/data/files/resized/fac/fac59bc172d8910e322e4dba56a6d41b1c4f514d: Image type not recognized: Unknown image type "['regular file']"
/src/astrometry/astrometry/net/models.py in get_pnm_path, line 443
```

Previously I had a problem with the image file not being chmodded correctly, but I can't seem to reproduce that issue.

[sky_plot/zoom3/1](http://35.202.61.141/sky_plot/zoom3/1) gives the following:
```
Exception Type: | SystemError
-- | --
NULL result without error in PyObject_Call
/src/astrometry/astrometry/libkd/spherematch.py in tree_open, line 392
```

Although I set `SOCIAL_AUTH_GITHUB_KEY` and `SOCIAL_AUTH_GITHUB_SECRET` in `settings.py`, the signin page looks like this.  I must be missing some setting:
![image](https://user-images.githubusercontent.com/310310/35207852-10c2d650-fefa-11e7-94f4-fe9242b71c70.png)

My instance is hosted at http://35.202.61.141/.  I'll keep it online as I mess around with things.

@gnthibault Have you run into any of these problems in your local instance?

**Comment by gnthibault** [comment]
@typpo Sorry, for now I am 100% using the API with default test accounts in the database.
If I use the web interface in the future, I'll report why I have.

**Comment by dstndstn** [comment]
Hi @typpo --

Regarding the first error: we use the "file" program to determine the file type of an uploaded file.  When I run the docker container with a regular FITS file, I get:

> docker run -p 8000:80 -it viewer
# apt-get install wget
# wget http://broiler.astrometry.net/~dstn/temp/img.fits
# file img.fits
img.fits: FITS image data, 8-bit, character or unsigned binary integer

it looks like you are getting "regular file" instead of "FITS image data", so then it doesn't know how to handle your image.  Or maybe it's the resized version that isn't working.  Could you please send a link to that file?

Oh, actually, when I try to look at the (un-annotated) image, http://35.202.61.141/image/3 , I get a reported PermissionDenied error.  It looks like the web server runs as the user "nova" (in apache2.conf), so the process_submissions.py script should run as that same user.

For the second problem, the skyplot, you need to download this file,
http://data.astrometry.net/tycho2.kd
and put it wherever astrometry/net/settings_common.py's TYCHO2_KD variable points to.

For the login problem: you might want to refer to the settings file for the live nova.astrometry.net site, https://github.com/dstndstn/astrometry.net/blob/master/net/settings_nova.py
 -- it looks like you might need

SOCIAL_AUTH_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
)
?

Thanks for the bug reports!
